production:
  adapter: mysql2
  database: redmine_default
  host: localhost
  port: 
  username: redmine_default
  password: root
  encoding: utf8

development:
  adapter: mysql
  database: redmine_default
  host: localhost
  port: 3306
  username: redmine_default
  password: root
  encoding: utf8
  
